name: Deploy Website
on:
  push:
    branches: [ main ] # Se ejecuta cada vez que subes cambios a 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to gh-pages branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4 for Node.js 24 compatibility

      - name: Inject Secrets into Code
        run: |
          sed -i "s|__GH_TOKEN__|${{ secrets.GH_TOKEN }}|g" js/github-service.js
          sed -i "s|__GH_USERNAME__|${{ secrets.GH_USERNAME }}|g" js/github-service.js
          sed -i "s|__GH_REPO_NAME__|${{ secrets.GH_REPO_NAME }}|g" js/github-service.js
          sed -i "s|__GH_PATH_IMG_LIMPIA__|${{ secrets.GH_PATH_IMG_LIMPIA }}|g" js/github-service.js
          sed -i "s|__GH_PATH_IMG_SIN_FONDO__|${{ secrets.GH_PATH_IMG_SIN_FONDO }}|g" js/github-service.js
          sed -i "s|__GH_PATH_IMG_CONDENSADA_SCENE__|${{ secrets.GH_PATH_IMG_CONDENSADA_SCENE }}|g" js/github-service.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Sube la carpeta raíz
          branch: gh-pages # Despliega a la rama gh-pages (activa GitHub Pages en esta rama)
